"""
Django settings for amazon_web project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fghc3@0%p8)fv8e54^o$bxmj@4jt4(k*gdclg04!2%jeghf^63'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["3.112.142.2","price-master.site"]

STATIC_ROOT='/usr/share/nginx/html/static'
MEDIA_ROOT='/usr/share/nginx/html/media'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'data_view',
    'my_page',
    'asin.apps.AsinConfig',
    'django_tables2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'amazon_web.middleware.auth.authMiddleware'
]


ROOT_URLCONF = 'amazon_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # templateをプロジェクト直下に配置するための設定
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amazon_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'amazon',
        'USER': 'db_admin',
        'PASSWORD': 'db_admin_amazon',
        'HOST': 'amazon-keepa.c6j7ziur63dw.ap-northeast-1.rds.amazonaws.com',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/


LANGUAGE_CODE = 'ja-jp'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# STATIC_ROOT = os.path.join(BASE_DIR, 'static') # プロジェクト直下にstaticを配置する
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_URL = '/static/'

# ログイン後トップページにリダイレクト
LOGIN_REDIRECT_URL = '/my_page/'
LOGIN_URL = 'login'

# STRIPE_SECRET_KEY = "sk_test_51HyaPtA9WmOGZ5uPuVS3r317Xr6hLrMuLnxoDbyVRQYXrVipUmNYpvGONoPv01LCkGceGHfon0XunAizJA7UJR2q00pvtwY2si"
# STRIPE_PUBLISHABLE_KEY = "pk_test_51HyaPtA9WmOGZ5uPt6PuSYJx6ZlVtOuH8f7qxIIHojhk5STwhrTOnnkmw7iMqws8DcoXxritKkaVOvV45MmB68g000yLHygluB"

STRIPE_SECRET_KEY = "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"
STRIPE_PUBLISHABLE_KEY = "pk_live_51IMnluHYwVcAFA1bjRubVTjYdsJo4SRqNdHIdM2nonFaKUBJsgahen0lkiJRMvh5kmb2VRGE2hVDqbLOUmRbBZ9p00EtOwtyPH"

# test API manager
#STRIPE_PUBLISHABLE_KEY="pk_test_51IMnluHYwVcAFA1bcSu37fR7RNdZxEr7osGkKbPZldhFX1dIl3WnzFT0DK89OEnDsuZ9oIuQJNsNKAym6iPFDScl00MKu1843y"
#STRIPE_SECRET_KEY="sk_test_51IMnluHYwVcAFA1b1wP2aSawCfA3WkXL0A6GFyCXv1gcMzAotRSywSe0r4D6Dy19qZnYtOweFsU3440wlocVXEoj00K73Oc7LJ"

# test cradit card
# 4242424242424242 | Visa | Any 3 digits | Any future date
# 4000056655665556 | Visa (debit) | Any 3 digits | Any future date
# 5555555555554444 | Mastercard | Any 3 digits | Any future date
# 2223003122003222 | Mastercard (2-series) | Any 3 digits | Any future date
# 5200828282828210 | Mastercard (debit) | Any 3 digits | Any future date
# 5105105105105100 | Mastercard (prepaid) | Any 3 digits | Any future date
# 378282246310005 | American Express | Any 4 digits | Any future date
# 371449635398431 | American Express | Any 4 digits | Any future date
# 6011111111111117 | Discover | Any 3 digits | Any future date
# 6011000990139424 | Discover | Any 3 digits | Any future date
# 3056930009020004 | Diners Club | Any 3 digits | Any future date
# 36227206271667 | Diners Club (14 digit card) | Any 3 digits | Any future date
# 3566002020360505 | JCB | Any 3 digits | Any future date
# 6200000000000005 | UnionPay | Any 3 digits | Any future date