version: '3.7'

services:
  db:
    container_name: amazon_web
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33306:3306" #ローカルのmysqlと重複しないようにローカル側は33306を用いる
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: amazon_web
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./docker/sql/dump.sql.gz:/docker-entrypoint-initdb.d/install_docker.sql.gz
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./docker/php-phpmyadmin.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=docker
      - PMA_PASSWORD=docker
    ports:
      - 10080:80